### ISSUE TITLE
Impossible to create a single transaction for two devices connected to the same DataServer

### ISSUE THREAD

**Issue by tobiasah** [zhinst/zhinst-toolkit#134]
Transactions are the way to go for changing multiple values in a row. 
In zhinst-toolkit the are implemented in the NodeTree class. Since every device creates its own NodeTree object a transaction is limited to the nodes of the device. 

in ziPython it is possible to change nodes of different devices within a single transaction, as long as they are connected through the same DataServer. 

It would be nice to support the same feature in toolkit. A possible implementation could be to add a set_transaction Generator  on the session that starts a transaction on each device/NodeTree and combines all the node-value pairs into one single `set` command at the end. 

```
device1 = session.connect_device("dev2345")
device2 = session.connect_device("dev5432")
with session.set_transaction():
    device1.a.b(1)
    device2.c.d("test")
```
would result in 

```
daq.set(("/dev2345/a/b", 1),("/dev5432/c/d","test"))
```

**Comment by markheik** [comment]
I like this idea.

Would devices (and their calls) not connected to the `session` used in `with`-context be ignored/executed/raising exception?

``````
device1 = session1.connect_device("dev2345")
device2 = session2.connect_device("dev5432")

with session1.set_transaction():
    device1.a.b(1)
    device2.c.d("test") <-- Call ignored/executed/raises an exception
```

**Comment by tobiasah** [comment]
They would just result in normal set commands meaning they will be executed normally.
We would need to introduce a global state if we would like to catch that since the sessions are completely independent from each other.

My personal preference would be to just allow it since we would restrict the usage otherwise. And there is no logical reason to forbid that. The idea with the transaction was that one can do what ever one wants within the with statement but all set commands to the device/session will be bundled into one single command at the end.

@YakBizzarro Do you have a different opinion?

**Comment by YakBizzarro** [comment]
Fine for me to not explicitly forbid it. We should address that in the documentation
