### ISSUE TITLE
awg.load_sequencer_program times out if the source string is empty

### ISSUE THREAD

**Issue by tobiasah** [zhinst/zhinst-toolkit#138]
If an empty source string is passed to the AWG module it does not start the compilation 

The function [awg.load_sequencer_program](https://github.com/zhinst/zhinst-toolkit/blob/7232bf0507d267b01efae91254c8f03db25583fa/src/zhinst/toolkit/driver/nodes/awg.py#L90) waits until the compiler flag indicates a successful compilation. This will always timeout with an empty string.

We should document that empty strings are not allowed and probably raise a Runtime Exception. (Not raising anything would be dangerous since it would indicate a successful upload.

**Comment by markheik** [comment]
I propose raising a `ValueError` with message saying empty string/program.
