### ISSUE TITLE
Enum values cannot be pickled

### ISSUE THREAD

**Issue by haroldmeerwaldt** [zhinst/zhinst-toolkit#149]
Description
-----------
Hi there,

If you get a value from a parameter that is an enumeration, you get an error when you try to pickle it, e.g.:
```python
Traceback (most recent call last):

  File "C:\Users\XXX\AppData\Local\Temp\ipykernel_14224\1814195601.py", line 1, in <cell line: 1>
    loads(dumps(uhfli.demods.demods0.adcselect()))

PicklingError: Can't pickle <enum '/dev2338/demods/0/adcselect'>: attribute lookup /dev2338/demods/0/adcselect on zhinst.toolkit.nodetree.node failed
```

Getting the value works fine. No mention of attribute lookup failed there.

We send the instrument's snapshot to a parameter monitor in another process and pickle the values.

How to reproduce
----------------
```python
from zhinst.qcodes.driver.devices import UHFLI
from zhinst.toolkit.driver.devices import UHFLI as tkUHFLI
from zhinst.toolkit import Session
from pickle import dumps, loads

session = Session("192.168.x.xxx", 8004)
tk_uhfli = tkUHFLI("DEVXXXX", "UHFLI", session)
uhfli = UHFLI(tk_uhfli, session, "uhfli")

uhfli.demods.demods0.adcselect()  # no problem
loads(dumps(uhfli.demods.demods0.adcselect()))  # pickling error
```

Environment info
----------------

- Python version: 3.9.7
- zhinst-toolkit version: 0.3.3
- LabOne version: 22.02.29711
- zhinst version: 22.2.29711

Device/system information (if applicable)
-----------------------------------------

Additional information
----------------------

**Comment by tobiasah** [comment]
@haroldmeerwaldt good point. 

The problem is that we do not hardcode the enums in our package but rather generate it on request based on what LabOne reports. We will try to implement a proper solution. If you have any suggestions how this could look you are welcome to contribute. 

In the mean time you can just use the `enum=False` kwarg to return a plain integer which should not cause any problem with pickle any more

**Comment by haroldmeerwaldt** [comment]
For now I monkey-patched the `get_parser` and `set_parser` of all parameters in our HDAWG and UHFLI:

```python
def take_value_if_enum(val):
    return val.value if isinstance(val, Enum) else val

# loop through parameters
try:
    if parameter.node_info.enum is not None:
        parameter.get_parser = take_value_if_enum
        parameter.set_parser = take_value_if_enum
except ValueError:  # invalid enum member name
    parameter.get_parser = take_value_if_enum
    parameter.set_parser = take_value_if_enum
except AttributeError:  # no ZIParameter
    pass
```

If you want to use the parser to handle the enums in zhinst.qcodes, it can be done in `zhinst.qcodes.qcodes_adaptions.init_nodetree` with inside the add_parameter part something like `get_parser=take_value_if_enum if info.enum is not None else None`.

**Comment by tobiasah** [comment]
With the next toolkit version 0.3.6 (release data is end of august) it will be possible to pickle enums
