### ISSUE TITLE
compile_sequence_program doesn't work properly for 1x4 channel grouping

### ISSUE THREAD

**Issue by 1nandi-abir2** [zhinst/zhinst-toolkit#179]
Description
-----------

The compile_sequence_program function raises an error when we try to play a wave on channel 3 or 4, even when the channel grouping is set to 1x4. 

`Traceback (most recent call last):
  File "C:\Users\Dr C Mitra\Downloads\AWG_INTERFACE_PYTHON.py", line 35, in <module>
    elf_file, info = device.awgs[0].compile_sequencer_program(awg_program)
  File "C:\Users\Dr C Mitra\AppData\Local\Programs\Python\Python39\lib\site-packages\zhinst\toolkit\driver\nodes\awg.py", line 136, in compile_sequencer_program
    return compile_seqc(
zhinst.core.errors.CoreError: Compilation failed: Compiler Error (line: 6): can't play channel 3, valid values for channel are from 1 to 2`

How to reproduce
----------------
`from zhinst.toolkit import Session

import numpy as np

session = Session('localhost')
device = session.connect_device("DEV8369")

OUT_CHANNEL = 0
AWG_CHANNEL = 0

device.system.awg.channelgrouping(1)
print(device.awgs)
with device.set_transaction():
    #device.sigouts[OUT_CHANNEL].on(True)
    device.sigouts[OUT_CHANNEL].range(1)
    device.sigouts[OUT_CHANNEL+1].range(1)
    device.awgs[1].outputs[AWG_CHANNEL].amplitude(0.5)
    #device.awgs[0].outputs[AWG_CHANNEL].modulation.mode(0)
    #device.awgs[0].time(0)
    #device.awgs[0].userregs(0)
    
from zhinst.toolkit import Sequence

AWG_N = 2000
awg_program = Sequence()
awg_program.constants["AWG_N"] = AWG_N
awg_program.code = """
wave w0 = gauss(AWG_N, AWG_N/2, AWG_N/20);
while(getUserReg(0) == 0) {
    playWave(3,w0);
}
"""
print(awg_program)
    
elf_file, info = device.awgs[0].compile_sequencer_program(awg_program)

print(info)
session.disconnect_device("DEV8369")`

Environment info
----------------

- Python version: 3.9.7
- zhinst-toolkit version: 0.4.1
- LabOne version: 22.08.35048
- zhinst version: 22.8.1

Device/system information (if applicable)
-----------------------------------------
4 channel HDAWG 750 MHz

Additional information
----------------------
The device.system.awg.channelgrouping function seems to be working properly as has been verified by running the code and observing the changes in the LabOne interface. It seems that the offline compiler which is used by the compile_sequence_program function doesn't take this change into account. We are facing a similar problem with the load_sequence_program function.

**Comment by tobiasah** [comment]
With 22.08 `zhinst-toolkit` switched to the offline compiler provided by the LabOne API. This offline compiler does not support channel grouping mode for now. 
I must admit that the documentation here is not very clear and we should update it accordingly!

Generally `zhinst-toolkit` does not provide functionality for the channelgrouping mode. Nevertheless, one can use it with channelgrouping mode but should not rely on the helper functions (e.g. `compile_sequencer_program`)

To compile (and optionally upload) an AWG program for channelgrouping mode one needs to fall back to the LabOne AWG module. 

The following code can be used to compile and upload a program with the LabOne AWG module through `zhinst-toolkit` 

```python
import time
from zhinst.toolkit import Session

session = Session("localhost")
device = session.connect_device("dev8369")
device.system.awg.channelgrouping(1)

awg = session.modules.awg
awg.device(device.serial)
awg.index(0)
awg.execute()
awg.compiler.sourcestring(awg_program.to_string())

# The following lines are not mandatory but only to ensure that everything was compiled and uploaded correctly. 
timeout = 100.0  # seconds
compiler_status = awg.compiler.status()
start = time.time()
while compiler_status == -1:
    if time.time() - start >= timeout:
        raise TimeoutError("Program compilation timed out")
    time.sleep(0.1)
    compiler_status = awg.compiler.status()
if compiler_status == 1:
    raise RuntimeError(
        "Error during sequencer compilation. Check the log for detailed information"
    )
if compiler_status == 2:
    print(f"Warning during sequencer compilation {awg.compiler.statusstring()}")
# Check and wait until the elf upload to the device was successful
progress = awg.progress()
while progress < 1.0 or awg.elf.status() == 2 or device.awgs[0].ready() == 0:
    if time.time() - start >= timeout:
        raise TimeoutError(f"Program upload timed out")
    time.sleep(0.1)
    progress = awg.progress()
if awg.elf.status() or not device.awgs[0].ready():
    raise RuntimeError(
        "Error during upload of ELF file. Check the log for detailed information"
    )
```

I will update the documentation accordingly. 

Please let me know if the code above solves the problem for you.

**Comment by 1nandi-abir2** [comment]
The solution works! Thanks a lot @tobiasah.
