### ISSUE TITLE
Wrong _device_type of awg node of UHFQA/UHFLI

### ISSUE THREAD

**Issue by MadSciSoCool** [zhinst/zhinst-toolkit#181]
Description
-----------
The device type of awg node in UHFQA is 0 rather than the name string

How to reproduce
----------------
```python
qa = session.connect_device("dev2571")
print(qa.awgs[0]._device_type)
```
Environment info
----------------

- Python version: 3.8.5
- zhinst-toolkit version: 0.4.1
- LabOne version: 22.2.29711
- zhinst version: 22.2.29711

Device/system information (if applicable)
-----------------------------------------
UHFQA

Additional information
----------------------
It seems this bug is due to wrong argument in uhfli.py, the index is feed to the device type when initializing awg node.

**Comment by tobiasah** [comment]
@MadSciSoCool  Thanks a lot for raising this issue. The arguments for initializing the awg node are indeed wrong. 
I create a PR (#182) that fixes this.
