### ISSUE TITLE
Block functions that enable and check the status of unit in transactional set

### ISSUE THREAD

**Issue by YakBizzarro** [zhinst/zhinst-toolkit#228]
In a transactional set, all the node setting are batched and sent together to the device only at the end of the block. That provide a significant speedup, but it's dangerous for functions that rely on the read value of a node.
For example, the `.run()` function start a scope, enable the scope and check that it successfully enabled. But in a transactional set, the enable set is merely batched, so the check fails unless the scope was already enabled.

Introduce a decorator to mark such function as unsuitable for a transactional set. That will prevent dangerous situation and enforce correct usage

@tobiasah

**Comment by tobiasah** [comment]
closed by #265
