### ISSUE TITLE
HDAWG4 | Allowed number of channels limited to 2 in grouping mode (1x4)

### ISSUE THREAD

**Issue by gauravag99** [zhinst/zhinst-toolkit#242]
Description
-----------
### What I want to do:
Play a time-varying Rabi sequence on outputs 1 and 2, then play a constant readout pulse on outputs 3 and 4.

The pulse sequence is something like this:
1. Play the control pulse of time 't' on outputs 1 and 2.
2. Play readout pulse after step 1 is finished on 3 and 4.
3. Wait for 1000 clock cycles, increment t-> t+dt, and go back to step 1.

### Problem:
Using HDAWG4 in grouping mode = 1 (i.e. 1x4), the outputs allowed should be 1 or 2 or 3, or 4. 
However, when using output number 3 or 4, on `assignWaveIndex(3,readout_pulse)` the following error is displayed on compilation:

```
Compilation failed: Compiler Error (line: 47): can't play channel 3, valid values for channel are from 1 to 2
``` 

Can anyone please guide me as to what can be done?

 I would also like the first marker on output 3 and the second marker on output 4 to be turned on with the readout pulse, however, trying to include an `11*markers=np.ones_like(readout)` does not seem to work.

## How to reproduce:
`control_pulses` is a list of pulses to be indexed and uploaded.
```
awg_program = Sequence()
awg_program.waveforms = Waveforms()

awg_program.waveforms.assign_waveform(0,wave1 = Wave(pul, name= f"readout_pulse"))
for i,pul in enumerate(control_pulses):
    awg_program.waveforms.assign_waveform(i+1,Wave(pul, name= f"rabi_{i+1}"))

awg_program.code = """
while (true) {

"""

for i in range(len(control_pulses)):
    awg_program.code += f"playWave(1, rabi_{i+1});\n"
    awg_program.code += f"waitWave();\nplayWave(3,readout);\n"
    awg_program.code += f"wait({wait_n});\n"

awg_program.code += '}'



elf_file, info = device.awgs[0].compile_sequencer_program(awg_program)
info
```
at this point the error comes up. If that weren't the case, I'd use the following:

```
with device.set_transaction():
    device.awgs[0].elf.data(elf_file, deep=True)
    device.awgs[0].write_to_waveform_memory(awg_program.waveforms)
    # device.awgs[1].write_to_waveform_memory(awg_program.waveforms)
    device.awgs[0].single(False)     #Repeat sequence
    device.awgs[0].enable(True)
 ```
Please let me know if waveforms also need to be uploaded to awg[1].

----------------

Environment info
----------------

- Python version: 3.10
- zhinst-toolkit version: 0.5.2
- LabOne version: 23.02
- zhinst version: 23.2.2

Device/system information (if applicable)
-----------------------------------------
Using HDAWG4

Additional information
----------------------

**Comment by tobiasah** [comment]
The AWG offline compiler does unfortunately not support channel grouping. 
When using channel grouping, you need to fall back to the LabOne AWG Module instead. 
An example code for toolkit can be found here (at the end of the subsection offline-compilation): 
https://docs.zhinst.com/zhinst-toolkit/en/latest/examples/awg.html#Offline-compilation

(The full documentation of the LabOne AWG Module can be found here https://docs.zhinst.com/labone_programming_manual/awg_module.html)

Without that limitation, your code would just work fine though 😇

**Comment by gauravag99** [comment]
Thanks @tobiasah, I will check it out.

Meanwhile, if I do operate on 2x2, is there a way to internally trigger the awgcore 2 by marker/trigger of awgcore1? Or any other way where I could set the sequence on awgcore 2 to wait for an event completion awgcore1?

**Comment by YakBizzarro** [comment]
Dear @gauravag99 ,
yes, in fact it's our recommended way. Please check out this blog post [Synchronizing Multiple AWG Channels](https://www.zhinst.com/blogs/synchronizing-multiple-awg-channels) , the section "2. Inter-core triggering" describe exactly what you asked.

In addition, let me suggest you to check also this blog post about efficient generation of control pulses: [Efficient Generation of Dynamic Pulses](https://www.zhinst.com/blogs/efficient-generation-dynamic-pulses). With the approach described here, you could generate on the fly the control pulses, reducing considerably the upload time of a sequence.

Let me know if that helps you, or feel free to reach me privately at [andreac@zhinst.com](mailto:andreac@zhinst.com) if you prefer.

**Comment by gauravag99** [comment]
Hi, I have recently encountered another problem. I am forced to use the offline compiler to be able to use the grouped mode. The offline compiler however returns the following error:

```
Compiler Error (line: 14006): Waveform allocation error: Waveforms requiring fixed allocation exceed cache memory size
```

I assumed that it would upload to the DDR memory on it's own? The total size of the waveforms I am trying to upload is quite below the advertised memory, so the only thing I could think of is that the compiler is not taking into account the instrument's DDR memory. I've attached the code I am using below:


Generating sequences below:
```
### Generate Ramsey sequences

piby2_pul_len = 20e-9
piby2_pul_amp = 1.0
init_t = 1e-9
fin_t = 1000e-9
incr_t = 5e-9
con_freq = 750e6

read_t = 1e-6
read_freq = 500e6
mark_len = 500              #in 2.4GHz rate
wait_n = 1000000               # in 3.3ns pts

control_pulses_I = []
control_pulses_Q = []
con_pul_len = []
marker_pulses = []

sclk = 2.4e9
t_list = np.arange(init_t,fin_t,incr_t)

biggest_pulse_I = gen_sin(con_freq,0,piby2_pul_amp,fin_t+2*piby2_pul_len,sclk)
biggest_pulse_Q = gen_sin(con_freq,np.pi/2,piby2_pul_amp,fin_t+2*piby2_pul_len,sclk)

for i in t_list:
    piby2_pts = int(sclk*piby2_pul_len)
    wait_pts = int(i*sclk)
    envelope = np.hstack((np.ones(piby2_pts),np.zeros(wait_pts),np.ones(piby2_pts)))
    pul = biggest_pulse_I[:wait_pts+2*piby2_pts]*envelope
    
    pul = round_off_wvf_to_16_wvfpoints(pul,front=True)
    control_pulses_I.append(pul)

    pul = biggest_pulse_Q[:wait_pts+2*piby2_pts]*np.hstack((np.ones(piby2_pts),np.zeros(wait_pts),np.ones(piby2_pts)))
    pul = round_off_wvf_to_16_wvfpoints(pul,front=True)
    control_pulses_Q.append(pul)

    con_pul_len.append(len(pul))
    mar = np.zeros_like(pul)
    mar[-30:-20] = 1
    marker_pulses.append(mar)

readout_pulse_I = round_off_wvf_to_16_wvfpoints(gen_sin(read_freq,0,1.0,read_t,sclk),back=True)
readout_pulse_Q = round_off_wvf_to_16_wvfpoints(gen_sin(read_freq,np.pi/2,1.0,read_t,sclk),back=True)

marker = np.append(np.ones(mark_len),np.zeros(readout_pulse_I.size-mark_len))
```

Finally trying to assign memory and compile:
```
awg_program = Sequence()
awg_program.waveforms = Waveforms()
awg_program.waveforms_read = Waveforms()

#add control pulses
for i, (pul_I, pul_Q) in enumerate(zip(control_pulses_I,control_pulses_Q)):
    awg_program.waveforms.assign_waveform(i+1,
                                        Wave(pul_I, name= f"ramsey_I_{i+1}"),
                                        Wave(pul_Q, name= f"ramsey_Q_{i+1}"),
                                        markers=marker_pulses[i])

#add readout pulse
awg_program.waveforms.assign_waveform(0,
                                        Wave(readout_pulse_I, name= f"readout_I"),
                                        Wave(readout_pulse_Q, name= f"readout_Q"),
                                        markers=15*marker)

awg_program.waveforms_read.assign_waveform(0,
                                        Wave(readout_pulse_I, name= f"readout_I1"),
                                        Wave(readout_pulse_Q, name= f"readout_Q1"),
                                        markers=15*marker)

awg_program.code = """
while (true) {

"""

#add placeholders to the sequence
awg_program.code += awg_program.waveforms.get_sequence_snippet()

for i in range(len(control_pulses_I)):
    awg_program.code += f"\n playWave(1,ramsey_I_{i+1},2,ramsey_Q_{i+1});\n waitWave();\n playWave(3,readout_I,4,readout_Q);\n wait({wait_n});"

awg_program.code += '}'
```

Finally compiling:
```
    awg_node = device.awgs[awgnode]
    awg = session.modules.awg
    awg.device(device.serial)
    awg.index(awgnode)
    awg.sequencertype('sg' if device.device_type.startswith('SHFSG') or device.device_type.startswith('SHFQC') else 'auto-detect')
    awg.execute()
    awg.compiler.sourcestring(code)

    # The following lines are not mandatory but only to ensure that everything was compiled and uploaded correctly. 
    timeout = 100.0  # seconds
    compiler_status = awg.compiler.status()
    start = time.time()
    while compiler_status == -1:
        if time.time() - start >= timeout:
            raise TimeoutError("Program compilation timed out")
        time.sleep(0.1)
        compiler_status = awg.compiler.status()
        if compiler_status == 1:
            print(awg.compiler.statusstring())
            raise RuntimeError(
                "Error during sequencer compilation. Check the log for detailed information"
            )
        if compiler_status == 2:
            print(f"Warning during sequencer compilation {awg.compiler.statusstring()}")
    # Check and wait until the elf upload to the device was successful
    print("Sequence loaded.")
    progress = awg.progress()
    while progress < 1.0 or awg.elf.status() == 2 or awg_node.ready() == 0:
        if time.time() - start >= timeout:
            raise TimeoutError(f"Program upload timed out")
        time.sleep(0.1)
        progress = awg.progress()
    if awg.elf.status() or not awg_node.ready():
        raise RuntimeError(
            "Error during upload of ELF file. Check the log for detailed information"
        )
    print("AWG ready for data upload.")
    ```
    
    Which is when I get the error.
    
    Is there any way around this? Due to the nature of further experiments, we have to upload arbitrary waveforms, and cannot use LabOne's internal waveform methods or use the command table.

**Comment by chunyanusername** [comment]
Hi Gaurav, 

I'm Chunyan, I will take over the case via email.

**Comment by gauravag99** [comment]
Hi, recieved your mails. I'll close this thread.
