### ISSUE TITLE
Cloudflare is blocking third party documentation builds that use intersphinx

### ISSUE THREAD

**Issue by rsokolewicz** [zhinst/zhinst-toolkit#278]
Hi,

I realize this isn't the best place to raise this, but I couldn't find another way of reaching out :') 

I'm one of the maintainers of quantify, and our package depends on a few zhinst packages. We have a GitLab pipeline that creates a sphinx documentation, and one of the plugins, `intersphinx`, creates a mapping between `zhinst` related objects and a hyperlink to the corresponding API page of your package. As of yesterday, we noticed that when we build the documentation with a GitLab runner we run into a 403 error, meaning our connection is refused. The error message we get is:

```
intersphinx inventory 'https://docs.zhinst.com/zhinst-toolkit/en/latest/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 403 Client Error: Forbidden for url: https://docs.zhinst.com/zhinst-toolkit/en/latest/objects.inv
WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://docs.zhinst.com/zhinst-qcodes/en/v0.1/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 403 Client Error: Forbidden for url: https://docs.zhinst.com/zhinst-qcodes/en/v0.1/objects.inv
```

building documentation locally works fine, it's only the GitLab runners that are being blocked. Could it be that CloudFlare or a firewall is blocking us? 

-----------

How to reproduce
----------------

Environment info
----------------

- Python version:
- zhinst-toolkit version:
- LabOne version:
- zhinst version:

Device/system information (if applicable)
-----------------------------------------

Additional information
----------------------

**Comment by tobiasah** [comment]
Hey
thanks for raising this issue.

We have had similar issues lately with other files 😇. Whitelisting the *.inv files on cloudflare should solve the problem. I have filed a request and keep you updated.

**Comment by rsokolewicz** [comment]
Hi Tobias, thanks! I just realized we have another pipeline failing during the `link-check` stage of sphinx. This checks all external URLs in our documentation to see if they are still alive/reachable. We are now also seeing 403 errors with that pipeline even when trying to reach the zhinst.com homepage. So if there is a solution beyond whitelisting *.inv files that would be nice 🥲

**Comment by tobiasah** [comment]
@rsokolewicz can you check if you still see a 403 error?

**Comment by rsokolewicz** [comment]
Hi Tobias, yes it all works now thank you very much :D
