### ISSUE TITLE
Incorrect documentation for custom awg sequence

### ISSUE THREAD

**Issue by ectof** [zhinst/zhinst-toolkit#3]
According to the documentation when parameters in a custom awg sequence should be written:

`$paramN$` where the index N begins from 0.

However, reading the source [here](https://github.com/zhinst/zhinst-toolkit/blob/master/zhinst/toolkit/helpers/sequences.py)

`
    def update_params(self):
        if self.path:
            self.program = Path(self.path).read_text()
        for i, p in enumerate(self.custom_params):
            self.program = self.program.replace(f"$param{i+1}$", str℗)
`
it appears that the index in the .seqc file should start from 1. This also seems to work in practice.

**Comment by tobiasah** [comment]
Thanks for reporting this issue. I do agree with you that the documentation was wrong.
We apologize for not responding in time. In the mean time the documentation has been updated and will be uploaded to our web server in a few days.
(See https://github.com/zhinst/zhinst-toolkit/blob/0ab12c926700772110973439a138e242dbc12205/src/zhinst/toolkit/helpers/sequences.py#L1097)
